services:
  - type: web
    name: eyeguard-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers=1 --worker-class=sync --timeout=120"
    envVars:
      - key: FLASK_ENV
        value: production
